use VickyDB;
CREATE TABLE GALLERY_BOARD (
    NO INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT,
    FILENAME VARCHAR(200),
    REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

use VickyDB;

DROP TABLE IF EXISTS VICKY_COMPANY;

CREATE TABLE VICKY_COMPANY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    COUNTRY VARCHAR(100),
    NAME VARCHAR(100),
    ENGLISH_NAME VARCHAR(200),
    APPLIED_BUILDINGS TEXT,
    INDUSTRIAL_BUILDINGS TEXT,
    LUXURY_PRODUCT VARCHAR(100),
    PROSPERITY_EFFECT TEXT
);