use VickyDB;
CREATE TABLE GALLERY_BOARD (
    NO INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT,
    FILENAME VARCHAR(200),
    REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);