use VickyDB;
CREATE TABLE GALLERY_BOARD (
    NO INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT,
    FILENAME VARCHAR(200),
    REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VICKY_COMPANY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    COUNTRY VARCHAR(100),
    NAME VARCHAR(100),
    ENGLISH_NAME VARCHAR(200),
    APPLIED_BUILDINGS TEXT,
    INDUSTRIAL_BUILDINGS TEXT,
    LUXURY_PRODUCT VARCHAR(100),
    PROSPERITY_EFFECT TEXT
);

CREATE TABLE MEMBER (
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    PASSWD VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO MEMBER (ID, PASSWD, NAME) VALUES ('admin', '1234', '관리자');

CREATE TABLE IF NOT EXISTS COMBINATION_LOG (
    LOG_ID INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID VARCHAR(50) NOT NULL,
    COMBINATION_NAME VARCHAR(100),
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMBINATION_ITEMS (
    LOG_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    PRIMARY KEY (LOG_ID, COMPANY_ID),
    FOREIGN KEY (LOG_ID) REFERENCES COMBINATION_LOG(LOG_ID) ON DELETE CASCADE,
    FOREIGN KEY (COMPANY_ID) REFERENCES VICKY_COMPANY(ID) ON DELETE CASCADE
);

CREATE TABLE VICTORIA_EVENTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    COUNTRY VARCHAR(50),
    YEAR INT,
    EVENT_NAME VARCHAR(200),
    TARGET VARCHAR(100),
    EVENT_TYPE VARCHAR(50)
);